"""add auth user tables

Revision ID: e4a13dd4f395
Revises:
Create Date: 2026-06-04 21:58:54.096997
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e4a13dd4f395"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("email_domain", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("department", sa.String(length=100), nullable=True),
        sa.Column("phone", sa.String(length=40), nullable=True),
        sa.Column("role", sa.String(length=40), server_default="employee", nullable=False),
        sa.Column(
            "status",
            sa.String(length=40),
            server_default="pending_email_verification",
            nullable=False,
        ),
        sa.Column("email_verified", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("auth_provider", sa.String(length=40), server_default="local", nullable=False),
        sa.Column("external_user_id", sa.String(length=120), nullable=True),
        sa.Column("ding_user_id", sa.String(length=120), nullable=True),
        sa.Column("employee_no", sa.String(length=80), nullable=True),
        sa.Column("failed_login_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_ip", sa.String(length=45), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "auth_provider IN ('local', 'dingtalk', 'external')", name="ck_users_auth_provider"
        ),
        sa.CheckConstraint(
            "email = lower(email)",
            name="ck_users_email_lowercase",
        ),
        sa.CheckConstraint(
            "email_domain = lower(email_domain)",
            name="ck_users_email_domain_lowercase",
        ),
        sa.CheckConstraint(
            "failed_login_count >= 0",
            name="ck_users_failed_login_count_non_negative",
        ),
        sa.CheckConstraint(
            "role IN ('employee', 'knowledge_admin', 'system_admin')", name="ck_users_role"
        ),
        sa.CheckConstraint(
            "status IN ('pending_email_verification', 'active', 'disabled', 'locked')",
            name="ck_users_status",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_users_email_domain", "users", ["email_domain"], unique=False)
    op.create_index("idx_users_role_status", "users", ["role", "status"], unique=False)
    op.create_index("idx_users_status", "users", ["status"], unique=False)
    op.create_index("uq_users_email", "users", ["email"], unique=True)
    op.create_table(
        "email_verification_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.CheckConstraint(
            "token_hash ~ '^[0-9a-f]{64}$'",
            name="ck_email_verification_tokens_token_hash_sha256_hex",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_email_verification_tokens_user_id",
        "email_verification_tokens",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "uq_email_verification_tokens_token_hash",
        "email_verification_tokens",
        ["token_hash"],
        unique=True,
    )
    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.CheckConstraint(
            "token_hash ~ '^[0-9a-f]{64}$'",
            name="ck_password_reset_tokens_token_hash_sha256_hex",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_password_reset_tokens_user_id", "password_reset_tokens", ["user_id"], unique=False
    )
    op.create_index(
        "uq_password_reset_tokens_token_hash", "password_reset_tokens", ["token_hash"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_password_reset_tokens_token_hash", table_name="password_reset_tokens")
    op.drop_index("idx_password_reset_tokens_user_id", table_name="password_reset_tokens")
    op.drop_table("password_reset_tokens")
    op.drop_index("uq_email_verification_tokens_token_hash", table_name="email_verification_tokens")
    op.drop_index("idx_email_verification_tokens_user_id", table_name="email_verification_tokens")
    op.drop_table("email_verification_tokens")
    op.drop_index("uq_users_email", table_name="users")
    op.drop_index("idx_users_status", table_name="users")
    op.drop_index("idx_users_role_status", table_name="users")
    op.drop_index("idx_users_email_domain", table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
