from __future__ import annotations

from enum import StrEnum


class ErrorCode(StrEnum):
    INTERNAL_ERROR = "INTERNAL_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"
    EMAIL_DOMAIN_NOT_ALLOWED = "EMAIL_DOMAIN_NOT_ALLOWED"
    EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED"
    INVALID_TOKEN = "INVALID_TOKEN"
    USER_DISABLED = "USER_DISABLED"
    USER_LOCKED = "USER_LOCKED"
    EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED"
    WEAK_PASSWORD = "WEAK_PASSWORD"
    RATE_LIMITED = "RATE_LIMITED"
    UPLOAD_DISABLED = "UPLOAD_DISABLED"
    FILE_EMPTY = "FILE_EMPTY"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    FILE_EXTENSION_NOT_ALLOWED = "FILE_EXTENSION_NOT_ALLOWED"
    FILE_MIME_NOT_ALLOWED = "FILE_MIME_NOT_ALLOWED"
    FILE_MIME_MISMATCH = "FILE_MIME_MISMATCH"
    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    FILE_VERSION_CONFLICT = "FILE_VERSION_CONFLICT"
    FILE_QUOTA_EXCEEDED = "FILE_QUOTA_EXCEEDED"
    STORAGE_ERROR = "STORAGE_ERROR"
    DEPARTMENT_NOT_FOUND = "DEPARTMENT_NOT_FOUND"
    DEPARTMENT_NAME_CONFLICT = "DEPARTMENT_NAME_CONFLICT"
    DEPARTMENT_CODE_CONFLICT = "DEPARTMENT_CODE_CONFLICT"
    DEPARTMENT_DISABLED = "DEPARTMENT_DISABLED"
    DEPARTMENT_ASSIGNMENT_REQUIRED = "DEPARTMENT_ASSIGNMENT_REQUIRED"
    UNASSIGNED_DEPARTMENT_IMMUTABLE = "UNASSIGNED_DEPARTMENT_IMMUTABLE"
    MANAGED_DEPARTMENTS_REQUIRE_DEPT_ADMIN = "MANAGED_DEPARTMENTS_REQUIRE_DEPT_ADMIN"
    REVIEW_CLAIM_CONFLICT = "REVIEW_CLAIM_CONFLICT"
    REVIEW_ALREADY_DECIDED = "REVIEW_ALREADY_DECIDED"
    REVIEW_CLAIM_REQUIRED = "REVIEW_CLAIM_REQUIRED"
    ANALYSIS_FAILED_SUBMISSION_DISABLED = "ANALYSIS_FAILED_SUBMISSION_DISABLED"
    SENSITIVE_RISK_ACKNOWLEDGEMENT_REQUIRED = "SENSITIVE_RISK_ACKNOWLEDGEMENT_REQUIRED"


class AppException(Exception):
    def __init__(self, error_code: ErrorCode, message: str) -> None:
        super().__init__(message)
        self.error_code = error_code
        self.message = message
