from __future__ import annotations

from enum import StrEnum


class ErrorCode(StrEnum):
    INTERNAL_ERROR = "INTERNAL_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"
    EMAIL_DOMAIN_NOT_ALLOWED = "EMAIL_DOMAIN_NOT_ALLOWED"
    EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED"
    INVALID_TOKEN = "INVALID_TOKEN"
    USER_DISABLED = "USER_DISABLED"
    USER_LOCKED = "USER_LOCKED"
    EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED"
    WEAK_PASSWORD = "WEAK_PASSWORD"
    RATE_LIMITED = "RATE_LIMITED"
    FILE_EMPTY = "FILE_EMPTY"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    FILE_EXTENSION_NOT_ALLOWED = "FILE_EXTENSION_NOT_ALLOWED"
    FILE_MIME_NOT_ALLOWED = "FILE_MIME_NOT_ALLOWED"
    FILE_MIME_MISMATCH = "FILE_MIME_MISMATCH"
    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    FILE_QUOTA_EXCEEDED = "FILE_QUOTA_EXCEEDED"
    STORAGE_ERROR = "STORAGE_ERROR"


class AppException(Exception):
    def __init__(self, error_code: ErrorCode, message: str) -> None:
        super().__init__(message)
        self.error_code = error_code
        self.message = message
